# Generated by Django 4.0.6 on 2022-07-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='addNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
